import { homepage } from './homepage'
import { careers } from './careers'
import { jobOpening } from './jobOpening'
import { jobCategory } from './jobCategory'
import { admission } from './admission'
import { doctor } from './doctor'
import { department } from './department'
import { specialty } from './specialty'
import aboutPage from './aboutPage'
import historyPage from './historyPage'
import healthAdvisory from './healthAdvisory'
import newsUpdate from './newsUpdate'
import { appointment } from './appointment'
import { scheduleLabPage } from './scheduleLabPage'
import { labTest } from './labTest'
import { labDepartment } from './labDepartment'
import { servicesPage } from './servicesPage'
import contactMessage from './contactMessage'

export const schemaTypes = [homepage, careers, jobOpening, jobCategory, admission, doctor, department, specialty, aboutPage, historyPage, healthAdvisory, newsUpdate, labDepartment, appointment, scheduleLabPage, labTest, servicesPage, contactMessage]
